#######    CONFIG TEMPLATE     #######
#
# This is a template for the config.yaml file.
# You can edit this file and remove all the parts you don't need.
# For the program to function you need to configure: 
#   - at least one container
#   - at least one notification service (Ntfy or Apprise)
#   - at least one keyword (either set globally or per container)
# The rest is optional or has default values.
#
# If you want to use this file after editing it make sure to rename it to config.yaml
#
# With every container exaample you can see some more available configuration options
#
# I did not include the option to customize notifications in this template but:
#   - Here is a detailed explanation on that: https://github.com/clemcer/loggifly/main#-customize-notifications-templates--log-filtering
#   - And here are some examples: https://github.com/clemcer/loggifly/blob/main/config_example.yaml

containers:

  container1: # leave blank if you only need global keywords

  container2: # must match exact container name
    keywords:
      - keyword1
      - keyword2

  container3:
    keywords:
      - regex: regex-patern       # this is how to set regex patterns
    keywords_with_attachment: # attach a logfile to the notification
      - keyword2
    action_keywords: # trigger a restart/stop of the container. can not be set globally
      - restart: keyword3
      - stop: keyword4
  
  container4:
  # The next 6 settings override the global values only for this container
    ntfy_tags: closed_lock_with_key   
    ntfy_priority: 5
    ntfy_topic: container4
    notification_title: '{keywords} found in {container}' # modify the notification title for this container
    attachment_lines: 50     
    notification_cooldown: 2  
    action_cooldown: 300

    keywords:
      - keyword1
    keywords_with_attachment:
      - keyword2
    action_keywords:  
      - stop: keyword3
      - restart: 
          regex: regex-pattern # this is how to set regex patterns for action_keywords
          
# Global keywords are applied to all containers
global_keywords:
  keywords:
    - global_keyword1
  keywords_with_attachment:
    - global_keyword2

notifications:                       
  # At least one of these (Ntfy/Apprise/Webhook) is required.
  ntfy:
    url: http://your-ntfy-server    # Required. The URL of your Ntfy instance
    topic: loggifly                 # Required. the topic for Ntfy
    token: ntfy-token               # Ntfy token in case you need authentication 
    username: john                  # Ntfy Username+Password in case you need authentication 
    password: password              # Ntfy Username+Password in case you need authentication 
    priority: 3                     # Ntfy priority (1-5)
    tags: kite,mag                  # Ntfy tags/emojis 
  apprise:
    url: "discord://webhook-url"    # Any Apprise-compatible URL (https://github.com/caronc/apprise/wiki)
  webhook: 
    url: https://custom.endpoint.com/post
    headers:                        # add headers if needed
      Authorization: "Bearer token"
      X-Custom-Header": "Test123"  

# These are the default settings
settings:          
  log_level: INFO               # DEBUG, INFO, WARNING, ERROR
  notification_cooldown: 5      # Seconds between alerts for same keyword (per container)
  action_cooldown: 300          # Cooldown period (in seconds) before the next container action can be performed. Maximum is always at least 60s.
  notification_title: default   # configure a custom template for the notification title (see section below)  attachment_lines: 20          # Number of Lines to include in log attachments
  multi_line_entries: True      # Monitor and catch multi-line log entries instead of going line by line. 
  reload_config: True           # When the config file is changed the program reloads the config
  disable_start_message: False  # Suppress startup notification
  disable_shutdown_message: False        # Suppress shutdown notification
  disable_config_reload_message: False   # Suppress config reload notification
  disable_container_event_message: False # Suppress notification when monitoring of containers start/stop
